# Generated by Django 6.0.2 on 2026-05-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('final_document', models.FileField(upload_to='archive/')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Архив',
                'verbose_name_plural': 'Архив',
            },
        ),
    ]
