# Generated by Django 6.0.2 on 2026-05-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Defense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defense_date', models.DateTimeField()),
                ('grade', models.CharField(max_length=10)),
                ('result', models.CharField(choices=[('passed', 'Защищено'), ('failed', 'Не защищено')], max_length=20)),
                ('comment', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Защита',
                'verbose_name_plural': 'Защиты',
            },
        ),
    ]
