# Generated by Django 6.0.2 on 2026-05-09 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('defenses', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='defense',
            name='commission',
            field=models.ManyToManyField(related_name='commissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='defense',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='defense', to='projects.project'),
        ),
    ]
